CC=gcc
CFLAGS=-g

all: quiz1 quiz2 quiz3
quiz1: quiz1.c
	$(CC) $(CFLAGS) -o $@ quiz1.c
quiz2: quiz2.c
	$(CC) $(CFLAGS) -o $@ quiz2.c
quiz3: quiz3.c
	$(CC) $(CFLAGS) -o $@ quiz3.c
clean:
	rm quiz1 quiz2 quiz3
