#define SBULL_MAGIC 'k'
#define SBULL_PRINT_INFO _IO(SBULL_MAGIC, 0)
#define SBULL_CLEAR_INFO _IO(SBULL_MAGIC, 1)
#define SBULL_ENABLE_COMPRESS _IO(SBULL_MAGIC, 2)
#define SBULL_DISABLE_COMPRESS _IO(SBULL_MAGIC, 3)
